package com.example.linter.data.youtube

import android.content.Context
import android.util.Log
import com.example.linter.data.local.ObjectBox
import com.example.linter.data.local.entity.SubtitleBlockEntity
import com.example.linter.data.local.entity.SubtitleBlockEntity_
import com.example.linter.data.local.entity.YoutubeVideoEntity
import com.example.linter.domain.model.SubtitleBlock
import com.example.linter.domain.model.TextTranslator
import com.example.linter.domain.model.VideoPlaybackInfo
import com.example.linter.domain.model.YoutubeVideo
import com.example.linter.domain.repository.YoutubeRepository
import com.example.linter.domain.model.TranslationMode
import kotlinx.coroutines.Dispatchers
import kotlinx.coroutines.withContext
import org.json.JSONObject
import org.schabi.newpipe.extractor.downloader.Request
import org.schabi.newpipe.extractor.stream.StreamInfo
import java.util.regex.Pattern
import kotlin.math.abs
import kotlin.math.roundToInt

class YoutubeRepositoryImpl(
    private val mlKitTranslator: TextTranslator,
    private val onnxTranslator: TextTranslator,
    context: Context // НОВОЕ
) : YoutubeRepository {

    private val videoBox get() = ObjectBox.store.boxFor(YoutubeVideoEntity::class.java)
    private val subtitleBox get() = ObjectBox.store.boxFor(SubtitleBlockEntity::class.java)
    private val prefs = context.getSharedPreferences("youtube_prefs", Context.MODE_PRIVATE)

    private val TAG = "LINTER_DEBUG"


    companion object {
        // Pre-compiling Regex to avoid compilation inside loop structures
        private val UNWANTED_CHARACTERS_REGEX = Regex("[^\\p{L}']")
        private val ENDS_WITH_PUNCTUATION_REGEX = Regex(".*[.!?,]$")
        private val XML_TEXT_TAG_PATTERN = java.util.regex.Pattern.compile("<text start=\"([\\d.]+)\"(?: dur=\"([\\d.]+)\")?[^>]*>(.*?)</text>", java.util.regex.Pattern.DOTALL)
        private val CLEAN_HTML_TAGS_REGEX = Regex("<[^>]*>")
        private val MULTIPLE_SPACES_REGEX = Regex("\\s+")
        private val RUSSIAN_PUNCTUATION_REGEX = Regex("[^а-яё]")
        private val SENTENCE_END_MATCH_REGEX = Regex(".*[,.!?;:][\"'\\]»]*$")
        private val VIDEO_ID_EXTRACTION_REGEX = Regex("(?:v=|youtu\\.be/|embed/|shorts/)([\\w-]{11})")
    }

    override fun getDefaultQuality(): String = prefs.getString("default_quality", "Auto") ?: "Auto"
    override fun setDefaultQuality(quality: String) = prefs.edit().putString("default_quality", quality).apply()

    override suspend fun deleteSubtitlesForVideo(videoId: Long) {
        withContext(Dispatchers.IO) {
            val blocksToRemove = subtitleBox.query(SubtitleBlockEntity_.youtubeVideoId.equal(videoId)).build().find()
            subtitleBox.remove(blocksToRemove)
        }
    }

    override suspend fun extractAndSaveVideo(url: String): Result<YoutubeVideo> = withContext(Dispatchers.IO) {
        try {
            val info = StreamInfo.getInfo(url)
            val entity = YoutubeVideoEntity(
                videoUrl = info.url,
                title = info.name,
                thumbnailUrl = info.thumbnails.firstOrNull()?.url ?: "",
                durationMs = info.duration * 1000L
            )
            val existing = videoBox.all.find { it.videoUrl == entity.videoUrl }
            val id = existing?.id ?: videoBox.put(entity)
            entity.id = id
            Result.success(entity.toDomain())
        } catch (e: Exception) {
            Result.failure(e)
        }
    }

    override suspend fun getSavedVideos(): List<YoutubeVideo> = withContext(Dispatchers.IO) { videoBox.all.map { it.toDomain() } }
    override suspend fun getVideoById(id: Long): YoutubeVideo? = withContext(Dispatchers.IO) { videoBox[id]?.toDomain() }

    override suspend fun updateProgress(id: Long, progressMs: Long) {
        withContext(Dispatchers.IO) {
            val entity = videoBox[id] ?: return@withContext
            entity.progressMs = progressMs
            videoBox.put(entity)
        }
    }

    override suspend fun deleteVideo(id: Long) {
        withContext(Dispatchers.IO) {
            deleteSubtitlesForVideo(id)
            videoBox.remove(id)
        }
    }

    override suspend fun fetchPlaybackInfo(videoId: Long, url: String, targetQuality: String): Result<VideoPlaybackInfo> = withContext(Dispatchers.IO) {
        try {
            Log.i(TAG, "🎬 [SUBTITLE_SOURCE] ЗАПУСК ВИДЕО ID: $videoId | Качество: $targetQuality")

            val info = StreamInfo.getInfo(url)
            val ytVideoId = extractVideoId(url) ?: throw Exception("Не удалось извлечь videoId")

            // =================================================================
            // 1. ОПРЕДЕЛЯЕМ ИСТИННЫЙ ОРИГИНАЛЬНЫЙ ЯЗЫК ВИДЕО
            // =================================================================
            var sourceLang = "en"
            var sourceUrl: String? = null

            val autoSub = info.subtitles.orEmpty().find { it.isAutoGenerated }
            if (autoSub != null) {
                sourceLang = autoSub.languageTag.substringBefore("-")
                sourceUrl = autoSub.url
            } else {
                val innertubeAsr = getInnertubeCaptionInfo(ytVideoId, targetLang = null)
                if (innertubeAsr != null) {
                    sourceUrl = innertubeAsr.first
                    sourceLang = innertubeAsr.second
                } else {
                    val audioLang = info.audioStreams.orEmpty().firstOrNull { it.audioLocale != null }?.audioLocale?.language
                    if (audioLang != null) sourceLang = audioLang
                }
            }

            val manualSub = info.subtitles.orEmpty().find { !it.isAutoGenerated && it.languageTag.startsWith(sourceLang, ignoreCase = true) }
            if (manualSub != null) {
                sourceUrl = manualSub.url
                sourceLang = manualSub.languageTag.substringBefore("-")
            } else if (sourceUrl == null) {
                val fallbackSub = info.subtitles.orEmpty().firstOrNull() ?: throw Exception("Субтитры отсутствуют полностью.")
                sourceUrl = fallbackSub.url
                sourceLang = fallbackSub.languageTag.substringBefore("-")
            }

            val finalSourceUrl = sourceUrl ?: throw Exception("Ссылка на субтитры пуста")

            // =================================================================
            // 2. БЕЗОПАСНЫЙ ВЫБОР АУДИО И ВИДЕО (ЗАЩИТА ОТ КРАШЕЙ)
            // =================================================================
            val allAudioStreams = info.audioStreams.orEmpty()
            val hasSeparateAudio = allAudioStreams.isNotEmpty()

            // Если отдельных аудиодорожек нет, мы ОБЯЗАНЫ брать видео со встроенным звуком (videoStreams),
            // иначе получим немое кино, взяв поток из videoOnlyStreams.
            val allVideoStreams = if (hasSeparateAudio) {
                info.videoOnlyStreams.orEmpty() + info.videoStreams.orEmpty()
            } else {
                info.videoStreams.orEmpty()
            }

            if (allVideoStreams.isEmpty()) throw Exception("Не найдены видеопотоки")

            val availableQualities = listOf("Auto") + allVideoStreams
                .mapNotNull { it.resolution }
                .distinct()
                .sortedByDescending { it.replace("p", "").toIntOrNull() ?: 0 }

            val targetRes = if (targetQuality == "Auto") "720p" else targetQuality

            val videoStream = allVideoStreams.filter { it.resolution == targetRes }.maxByOrNull { it.bitrate }
                ?: allVideoStreams.filter { it.resolution == "720p" }.maxByOrNull { it.bitrate }
                ?: allVideoStreams.maxByOrNull { it.resolution?.replace("p", "")?.toIntOrNull() ?: 0 }
                ?: allVideoStreams.first()

            val audioStream = allAudioStreams.filter { it.audioLocale?.language?.startsWith(sourceLang, true) == true }.maxByOrNull { it.averageBitrate }
                ?: allAudioStreams.filter { it.audioLocale == null }.maxByOrNull { it.averageBitrate }
                ?: allAudioStreams.maxByOrNull { it.averageBitrate }

            // БЕЗОПАСНЫЙ ФОЛБЭК: Если аудиопоток не найден, берем ссылку на видео (в нем уже есть встроенный звук)
            val finalAudioUrl = audioStream?.url ?: videoStream.url
            Log.i(TAG, "🎙️ [SUBTITLE_SOURCE] Выбран аудиопоток: ${audioStream?.audioLocale?.language ?: "Встроенный в видео"}")

            // =================================================================
            // 3. ПРОВЕРКА КЭША
            // =================================================================
            val cachedEntities = subtitleBox.query(SubtitleBlockEntity_.youtubeVideoId.equal(videoId)).build().find()
            if (cachedEntities.isNotEmpty()) {
                val domainBlocks = cachedEntities.map {
                    SubtitleBlock(it.id, it.startTimeMs, it.endTimeMs, it.sourceText, it.translatedText, it.mlKitTranslatedText, it.onnxTranslatedText)
                }.sortedBy { it.startTimeMs }

                // ИСПРАВЛЕНИЕ: Проверяем, действительно ли в кэше есть переводы от YouTube (translatedText)
                val hasYtTranslation = domainBlocks.any { !it.translatedText.isNullOrBlank() }

                return@withContext Result.success(VideoPlaybackInfo(
                    videoStream.url.toString(),
                    finalAudioUrl.toString(),
                    domainBlocks,
                    hasYtTranslation, // <-- Теперь здесь динамическая проверка, а не жесткий true
                    sourceLang,
                    availableQualities
                ))
            }

            // =================================================================
            // 4. СКАЧИВАНИЕ И СМАРТ-ЧАНКИНГ ОРИГИНАЛА
            // =================================================================
            val rawSourceBlocks = fetchAndParseBlocks(finalSourceUrl)
            if (rawSourceBlocks.isEmpty()) throw Exception("Не удалось распарсить субтитры.")
            val smartSourceBlocks = buildAestheticSubtitles(rawSourceBlocks)

            // =================================================================
            // 5. ПОЛУЧЕНИЕ ПЕРЕВОДА (RU)
            // =================================================================
            var ruBlocks = emptyList<SubtitleBlock>()
            try {
                if (sourceLang.startsWith("ru", true)) {
                    ruBlocks = smartSourceBlocks
                } else {
                    val nativeRuUrl = info.subtitles.orEmpty().find { !it.isAutoGenerated && it.languageTag.startsWith("ru", ignoreCase = true) }?.url
                    if (nativeRuUrl != null) {
                        ruBlocks = fetchAndParseBlocks(nativeRuUrl)
                    } else {
                        val ruUrl = if (finalSourceUrl.contains("tlang=")) finalSourceUrl else "$finalSourceUrl&tlang=ru"
                        try {
                            ruBlocks = fetchAndParseBlocks(ruUrl)
                        } catch (e: Exception) {
                            val innertubeRuUrl = getInnertubeCaptionInfo(ytVideoId, targetLang = "ru")?.first
                            if (innertubeRuUrl != null) ruBlocks = fetchAndParseBlocks(innertubeRuUrl)
                        }
                    }
                }
            } catch (e: Exception) {}

            // =================================================================
            // 6. СЛИЯНИЕ И СОХРАНЕНИЕ
            // =================================================================
            val mergedBlocks = if (ruBlocks.isNotEmpty()) mergeSubtitles(smartSourceBlocks, ruBlocks) else smartSourceBlocks

            val entitiesToSave = mergedBlocks.map {
                SubtitleBlockEntity(
                    youtubeVideoId = videoId,
                    startTimeMs = it.startTimeMs,
                    endTimeMs = it.endTimeMs,
                    sourceText = it.sourceText,
                    translatedText = it.translatedText
                )
            }
            subtitleBox.put(entitiesToSave)

            val savedBlocks = subtitleBox.query(SubtitleBlockEntity_.youtubeVideoId.equal(videoId)).build().find()
                .map { SubtitleBlock(it.id, it.startTimeMs, it.endTimeMs, it.sourceText, it.translatedText, it.mlKitTranslatedText, it.onnxTranslatedText) }
                .sortedBy { it.startTimeMs }

            Result.success(
                VideoPlaybackInfo(
                    videoUrl = videoStream.url.toString(),
                    audioUrl = finalAudioUrl.toString(),
                    subtitles = savedBlocks,
                    hasYoutubeTranslation = ruBlocks.isNotEmpty(),
                    sourceLang = sourceLang,
                    availableQualities = availableQualities
                )
            )
        } catch (e: Exception) {
            Log.e(TAG, "❌ КРИТИЧЕСКАЯ ОШИБКА: ${e.message}")
            Result.failure(e)
        }
    }

    override suspend fun translateAndSaveBlockLocally(block: SubtitleBlock, sourceLang: String, mode: TranslationMode): SubtitleBlock = withContext(Dispatchers.IO) {
        val activeTranslator = if (mode == TranslationMode.ADVANCED_ONNX) onnxTranslator else mlKitTranslator
        val translation = activeTranslator.translate(block.sourceText, sourceLang, "ru").getOrNull()

        val updatedBlock = if (mode == TranslationMode.ADVANCED_ONNX) {
            block.copy(onnxTranslatedText = translation ?: "Ошибка перевода")
        } else {
            block.copy(mlKitTranslatedText = translation ?: "Ошибка перевода")
        }

        val entity = subtitleBox.get(block.id)
        if (entity != null) {
            if (mode == TranslationMode.ADVANCED_ONNX) entity.onnxTranslatedText = updatedBlock.onnxTranslatedText
            else entity.mlKitTranslatedText = updatedBlock.mlKitTranslatedText
            subtitleBox.put(entity)
        }
        updatedBlock
    }

    // =======================================================================
    // СМАРТ-ЧАНКИНГ (СИНТАКСИЧЕСКОЕ РАЗБИЕНИЕ)
    // =======================================================================

    private data class TimedWord(val text: String, val start: Long, val end: Long)

    private fun buildAestheticSubtitles(rawBlocks: List<SubtitleBlock>): List<SubtitleBlock> {
        if (rawBlocks.isEmpty()) return emptyList()

        val allWords = mutableListOf<TimedWord>()
        for (block in rawBlocks) {
            val words = block.sourceText.split(Regex("\\s+")).filter { it.isNotBlank() }
            if (words.isEmpty()) continue

            val duration = maxOf(1L, block.endTimeMs - block.startTimeMs)
            val timePerWord = duration / words.size

            words.forEachIndexed { i, word ->
                allWords.add(TimedWord(
                    text = word,
                    start = block.startTimeMs + (i * timePerWord),
                    end = block.startTimeMs + ((i + 1) * timePerWord)
                ))
            }
        }

        val logicalSentences = mutableListOf<List<TimedWord>>()
        var currentSentence = mutableListOf<TimedWord>()

        for (i in allWords.indices) {
            val word = allWords[i]
            currentSentence.add(word)

            val endsWithPunctuation = word.text.lastOrNull() in listOf('.', '!', '?')
            val isNextWordFar = if (i < allWords.size - 1) {
                (allWords[i + 1].start - word.end) > 1500L
            } else false

            val isTooLong = currentSentence.joinToString(" ") { it.text }.length > 150

            if (endsWithPunctuation || isNextWordFar || isTooLong) {
                logicalSentences.add(currentSentence)
                currentSentence = mutableListOf()
            }
        }
        if (currentSentence.isNotEmpty()) logicalSentences.add(currentSentence)

        var idCounter = 0L
        val finalBlocks = mutableListOf<SubtitleBlock>()

        for (sentence in logicalSentences) {
            val chunks = splitSentenceSmartly(sentence)
            for (chunk in chunks) {
                if (chunk.isEmpty()) continue
                finalBlocks.add(SubtitleBlock(
                    id = idCounter++,
                    startTimeMs = chunk.first().start,
                    endTimeMs = chunk.last().end,
                    sourceText = chunk.joinToString(" ") { it.text }
                ))
            }
        }

        return finalBlocks
    }

    // =======================================================================
    // СМАРТ-ЧАНКИНГ (СИНТАКСИЧЕСКОЕ РАЗБИЕНИЕ)
    // =======================================================================

    private fun splitSentenceSmartly(sentence: List<TimedWord>): List<List<TimedWord>> {
        val text = sentence.joinToString(" ") { it.text }

        if (text.length <= 85 || sentence.size <= 5) {
            return listOf(sentence)
        }

        var bestSplitIndex = -1
        var maxScore = Int.MIN_VALUE

        val conjunctions = setOf(
            "and", "but", "so", "because", "until", "while", "after", "before", "when", "which", "that", "who", "where", "if",
            "et", "ou", "mais", "donc", "car", "parce", "que", "qui", "quand", "si", "comme", "puisque"
        )
        val orphans = setOf(
            "a", "an", "the", "in", "on", "at", "to", "for", "of", "with", "by", "from", "is", "are", "was", "were", "am", "i", "you", "he", "she", "it", "we", "they", "my", "your", "his", "her", "our", "their",
            "le", "la", "les", "un", "une", "des", "de", "du", "d'", "l'", "à", "au", "aux", "dans", "sur", "en", "vers", "avec", "sans", "sous", "par", "pour", "je", "tu", "il", "elle", "on", "nous", "vous", "ils", "elles", "mon", "ton", "son", "ma", "ta", "sa", "mes", "tes", "ses", "est", "sont", "suis", "es", "c'", "c", "qu'", "qu"
        )

        for (i in 2 until sentence.size - 2) {
            var score = 0

            val wordBeforeRaw = sentence[i - 1].text
            val wordAfterRaw = sentence[i].text

            // Using static pre-compiled regex objects
            val wordBefore = wordBeforeRaw.lowercase().replace(UNWANTED_CHARACTERS_REGEX, "")
            val wordAfter = wordAfterRaw.lowercase().replace(UNWANTED_CHARACTERS_REGEX, "")

            if (wordBeforeRaw.endsWith(",")) score += 100
            if (wordBeforeRaw.endsWith(";") || wordBeforeRaw.endsWith("-")) score += 80
            if (wordAfter in conjunctions) score += 90

            if (wordBefore in orphans) score -= 500
            if (wordAfterRaw.matches(ENDS_WITH_PUNCTUATION_REGEX)) score -= 500

            val leftSize = i
            val rightSize = sentence.size - i

            if (leftSize < 3 || rightSize < 3) score -= 1000

            val diff = kotlin.math.abs(leftSize - rightSize)
            score -= (diff * 5)

            if (score > maxScore) {
                maxScore = score
                bestSplitIndex = i
            }
        }

        if (bestSplitIndex == -1 || maxScore <= -100) {
            bestSplitIndex = sentence.size / 2
        }

        val leftChunk = sentence.subList(0, bestSplitIndex)
        val rightChunk = sentence.subList(bestSplitIndex, sentence.size)

        val result = mutableListOf<List<TimedWord>>()
        result.addAll(splitSentenceSmartly(leftChunk))
        result.addAll(splitSentenceSmartly(rightChunk))

        return result
    }

    private fun mergeSubtitles(smartSourceBlocks: List<SubtitleBlock>, rawRuBlocks: List<SubtitleBlock>): List<SubtitleBlock> {
        if (smartSourceBlocks.isEmpty() || rawRuBlocks.isEmpty()) return smartSourceBlocks

        val ruWords = mutableListOf<TimedWord>()
        for (ru in rawRuBlocks) {
            val words = ru.sourceText.split(MULTIPLE_SPACES_REGEX).filter { it.isNotBlank() }
            if (words.isEmpty()) continue
            val duration = maxOf(1L, ru.endTimeMs - ru.startTimeMs)
            val timePerWord = duration / words.size
            words.forEachIndexed { i, w ->
                ruWords.add(TimedWord(w, ru.startTimeMs + (i * timePerWord), ru.startTimeMs + ((i + 1) * timePerWord)))
            }
        }

        val blockAllocations = Array(smartSourceBlocks.size) { mutableListOf<TimedWord>() }
        for (ruWord in ruWords) {
            val wordCenter = (ruWord.start + ruWord.end) / 2
            var bestIndex = -1
            var minDistance = Long.MAX_VALUE

            for (i in smartSourceBlocks.indices) {
                val smart = smartSourceBlocks[i]
                if (wordCenter in smart.startTimeMs..smart.endTimeMs) {
                    bestIndex = i
                    break
                } else {
                    val dist = minOf(kotlin.math.abs(wordCenter - smart.startTimeMs), kotlin.math.abs(wordCenter - smart.endTimeMs))
                    if (dist < minDistance) {
                        minDistance = dist
                        bestIndex = i
                    }
                }
            }
            if (bestIndex != -1) blockAllocations[bestIndex].add(ruWord)
        }

        val ruConjunctions = setOf("и", "а", "но", "да", "или", "либо", "что", "чтобы", "как", "если", "хотя", "где", "когда", "который", "которая", "потому", "поэтому", "так", "затем", "потом", "ведь", "чем")
        val ruDangling = setOf("в", "на", "с", "к", "от", "из", "у", "за", "над", "под", "о", "об", "для", "до", "без", "не", "ни")

        for (i in 0 until smartSourceBlocks.size - 1) {
            val currentWords = blockAllocations[i]
            val nextWords = blockAllocations[i + 1]

            if (currentWords.isEmpty() && nextWords.isEmpty()) continue

            val windowSize = 4
            val leftPart = currentWords.takeLast(windowSize)
            val rightPart = nextWords.take(windowSize)
            val window = leftPart + rightPart

            if (window.isEmpty()) continue

            val originalCutIndex = leftPart.size
            var bestCutIndex = originalCutIndex
            var maxScore = -1000

            for (k in 1 until window.size) {
                var score = 0
                val wordBefore = window[k - 1].text.lowercase()
                val wordAfter = window[k].text.lowercase()
                val cleanWordBefore = wordBefore.replace(RUSSIAN_PUNCTUATION_REGEX, "")
                val cleanWordAfter = wordAfter.replace(RUSSIAN_PUNCTUATION_REGEX, "")

                if (wordBefore.matches(SENTENCE_END_MATCH_REGEX)) score += 100
                if (cleanWordAfter in ruConjunctions) score += 50
                if (cleanWordBefore in ruDangling) score -= 200
                if (cleanWordAfter in ruDangling) score += 20

                val distance = kotlin.math.abs(k - originalCutIndex)
                score -= (distance * 15)

                if (score > maxScore) {
                    maxScore = score
                    bestCutIndex = k
                }
            }

            if (bestCutIndex != originalCutIndex && maxScore > -500) {
                val shift = bestCutIndex - originalCutIndex
                if (shift > 0) {
                    val wordsToMove = nextWords.take(shift)
                    currentWords.addAll(wordsToMove)
                    blockAllocations[i + 1] = nextWords.drop(shift).toMutableList()
                } else {
                    val absShift = kotlin.math.abs(shift)
                    val wordsToMove = currentWords.takeLast(absShift)
                    nextWords.addAll(0, wordsToMove)
                    blockAllocations[i] = currentWords.dropLast(absShift).toMutableList()
                }
            }
        }

        return smartSourceBlocks.mapIndexed { i, smart ->
            val mergedText = blockAllocations[i].joinToString(" ") { it.text }.takeIf { it.isNotBlank() }
            smart.copy(translatedText = mergedText)
        }
    }

    private fun getInnertubeCaptionInfo(videoId: String, targetLang: String? = null): Pair<String, String>? {
        try {
            val body = JSONObject().apply {
                put("videoId", videoId)
                put("context", JSONObject().apply {
                    put("client", JSONObject().apply {
                        put("clientName", "WEB")
                        put("clientVersion", "2.20250601.01.00")
                        put("hl", "en") // Важно использовать "en", чтобы не было багов с локализацией
                    })
                })
            }

            val request = Request(
                "POST",
                "https://www.youtube.com/youtubei/v1/player",
                mapOf(
                    "Content-Type" to listOf("application/json"),
                    "User-Agent" to listOf("Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36")
                ),
                body.toString().toByteArray(Charsets.UTF_8),
                null,
                false
            )

            val response = NewPipeDownloader.getInstance().execute(request)
            if (response.responseCode() in 200..299) {
                val json = JSONObject(response.responseBody())
                val tracks = json.optJSONObject("captions")
                    ?.optJSONObject("playerCaptionsTracklistRenderer")
                    ?.optJSONArray("captionTracks") ?: return null

                var bestTrack: JSONObject? = null

                if (targetLang != null) {
                    // Ищем ручные сабы для целевого языка
                    for (i in 0 until tracks.length()) {
                        val t = tracks.optJSONObject(i) ?: continue
                        val vssId = t.optString("vssId", "")
                        if (t.optString("languageCode").startsWith(targetLang, ignoreCase = true) && !vssId.startsWith("a.")) {
                            bestTrack = t
                            break
                        }
                    }
                    // Если нет ручных, берем любые (например, переведенные авто)
                    if (bestTrack == null) {
                        for (i in 0 until tracks.length()) {
                            val t = tracks.optJSONObject(i) ?: continue
                            if (t.optString("languageCode").startsWith(targetLang, ignoreCase = true)) {
                                bestTrack = t
                                break
                            }
                        }
                    }
                } else {
                    // ИЩЕМ ОРИГИНАЛЬНЫЙ ЯЗЫК АУДИО (ASR)
                    for (i in 0 until tracks.length()) {
                        val t = tracks.optJSONObject(i) ?: continue
                        val vssId = t.optString("vssId", "")
                        val kind = t.optString("kind", "")
                        // vssId начинается с "a." означает auto-generated (сгенерировано движком YouTube).
                        // Это 100% гарантия того, что это оригинальный язык речи.
                        if (kind == "asr" || vssId.startsWith("a.")) {
                            bestTrack = t
                            break
                        }
                    }
                }

                if (bestTrack != null) {
                    var url = bestTrack.optString("baseUrl")
                    val lang = bestTrack.optString("languageCode").substringBefore("-")

                    if (targetLang != null && !url.contains("tlang=")) {
                        url += if (url.contains("?")) "&tlang=$targetLang" else "?tlang=$targetLang"
                    }
                    url = url.replace(Regex("fmt=[^&]+"), "fmt=json3").let {
                        if (!it.contains("fmt=json3")) "$it&fmt=json3" else it
                    }
                    return Pair(url, lang)
                }
            }
        } catch (e: Exception) {
            e.printStackTrace()
        }
        return null
    }

    // ====================== ПАРСИНГ И СКАЧИВАНИЕ ======================

    private fun fetchAndParseBlocks(url: String): List<SubtitleBlock> {
        val urlsToTry = listOf(
            url.replace(Regex("fmt=[^&]+"), "fmt=json3").let { if (!it.contains("fmt=json3")) "$it&fmt=json3" else it },
            url.replace(Regex("fmt=[^&]+"), "fmt=srv1").let { if (!it.contains("fmt=srv1")) "$it&fmt=srv1" else it }
        )

        for (u in urlsToTry) {
            try {
                val raw = downloadString(u)
                val jsonBlocks = parseJson3(raw)
                if (jsonBlocks.isNotEmpty()) return jsonBlocks

                val xmlBlocks = parseSubtitles(raw)
                if (xmlBlocks.isNotEmpty()) return xmlBlocks
            } catch (e: Exception) { continue }
        }
        return emptyList()
    }

    private fun downloadString(urlStr: String): String {
        val request = Request("GET", urlStr, emptyMap(), null, null, false)
        val response = NewPipeDownloader.getInstance().execute(request)
        val code = response.responseCode()
        if (code in 200..299) return response.responseBody() else throw Exception("HTTP $code")
    }

    private fun parseJson3(json: String): List<SubtitleBlock> {
        val blocks = mutableListOf<SubtitleBlock>()
        try {
            val root = JSONObject(json)
            val events = root.optJSONArray("events") ?: return blocks
            var id = 0L

            for (i in 0 until events.length()) {
                val event = events.optJSONObject(i) ?: continue
                val startMs = event.optLong("tStartMs", 0L)
                val durMs = event.optLong("dDurationMs", 0L)
                val segs = event.optJSONArray("segs") ?: continue

                val text = buildString {
                    for (j in 0 until segs.length()) append(segs.optJSONObject(j)?.optString("utf8", ""))
                }.replace("\n", " ").trim()

                if (text.isBlank()) continue

                blocks.add(SubtitleBlock(id++, startMs, startMs + durMs, text))
            }
        } catch (e: Exception) { }
        return blocks
    }

    private fun parseSubtitles(xml: String): List<SubtitleBlock> {
        val blocks = mutableListOf<SubtitleBlock>()
        val matcher = XML_TEXT_TAG_PATTERN.matcher(xml)
        var id = 0L

        while (matcher.find()) {
            val startSec = matcher.group(1)?.toFloatOrNull() ?: continue
            val durSec = matcher.group(2)?.toFloatOrNull() ?: 2.0f
            var text = matcher.group(3) ?: continue

            text = text.replace("&amp;", "&")
                .replace("&quot;", "\"")
                .replace("&#39;", "'")
                .replace("&lt;", "<")
                .replace("&gt;", ">")
                .replace("\n", " ")
                .replace(CLEAN_HTML_TAGS_REGEX, "")
                .trim()
            if (text.isBlank()) continue
            blocks.add(SubtitleBlock(id++, (startSec * 1000).toLong(), ((startSec + durSec) * 1000).toLong(), text))
        }
        return blocks
    }

    private fun extractVideoId(url: String): String? {
        return VIDEO_ID_EXTRACTION_REGEX.find(url)?.groupValues?.get(1)
    }

    private fun YoutubeVideoEntity.toDomain() = YoutubeVideo(id, videoUrl, title, thumbnailUrl, progressMs, durationMs)
}