package com.example.linter.data.youtube

import android.util.Log
import com.example.linter.data.local.ObjectBox
import com.example.linter.data.local.entity.SubtitleBlockEntity
import com.example.linter.data.local.entity.SubtitleBlockEntity_
import com.example.linter.data.local.entity.YoutubeVideoEntity
import com.example.linter.domain.model.SubtitleBlock
import com.example.linter.domain.model.TextTranslator
import com.example.linter.domain.model.VideoPlaybackInfo
import com.example.linter.domain.model.YoutubeVideo
import com.example.linter.domain.repository.YoutubeRepository
import kotlinx.coroutines.Dispatchers
import kotlinx.coroutines.withContext
import org.json.JSONObject
import org.schabi.newpipe.extractor.downloader.Request
import org.schabi.newpipe.extractor.stream.StreamInfo
import java.util.regex.Pattern
import kotlin.math.abs
import kotlin.math.roundToInt

class YoutubeRepositoryImpl(
    private val translator: TextTranslator
) : YoutubeRepository {

    private val videoBox get() = ObjectBox.store.boxFor(YoutubeVideoEntity::class.java)
    private val subtitleBox get() = ObjectBox.store.boxFor(SubtitleBlockEntity::class.java)

    private val TAG = "LINTER_DEBUG"

    override suspend fun extractAndSaveVideo(url: String): Result<YoutubeVideo> = withContext(Dispatchers.IO) {
        try {
            val info = StreamInfo.getInfo(url)
            val entity = YoutubeVideoEntity(
                videoUrl = info.url,
                title = info.name,
                thumbnailUrl = info.thumbnails.firstOrNull()?.url ?: "",
                durationMs = info.duration * 1000L
            )
            val existing = videoBox.all.find { it.videoUrl == entity.videoUrl }
            val id = existing?.id ?: videoBox.put(entity)
            entity.id = id
            Result.success(entity.toDomain())
        } catch (e: Exception) {
            Result.failure(e)
        }
    }

    override suspend fun getSavedVideos(): List<YoutubeVideo> = withContext(Dispatchers.IO) { videoBox.all.map { it.toDomain() } }
    override suspend fun getVideoById(id: Long): YoutubeVideo? = withContext(Dispatchers.IO) { videoBox[id]?.toDomain() }

    override suspend fun updateProgress(id: Long, progressMs: Long) {
        withContext(Dispatchers.IO) {
            val entity = videoBox[id] ?: return@withContext
            entity.progressMs = progressMs
            videoBox.put(entity)
        }
    }

    override suspend fun deleteVideo(id: Long) {
        withContext(Dispatchers.IO) {
            val blocksToRemove = subtitleBox.query(SubtitleBlockEntity_.youtubeVideoId.equal(id)).build().find()
            subtitleBox.remove(blocksToRemove)
            videoBox.remove(id)
        }
    }

    override suspend fun fetchPlaybackInfo(videoId: Long, url: String): Result<VideoPlaybackInfo> = withContext(Dispatchers.IO) {
        try {
            Log.i(TAG, "===================================================")
            Log.i(TAG, "🎬 [SUBTITLE_SOURCE] ЗАПУСК ВИДЕО ID: $videoId")

            val info = StreamInfo.getInfo(url)
            val ytVideoId = extractVideoId(url) ?: throw Exception("Не удалось извлечь videoId")

            // =================================================================
            // 1. ОПРЕДЕЛЯЕМ ИСТИННЫЙ ОРИГИНАЛЬНЫЙ ЯЗЫК ВИДЕО
            // =================================================================
            var sourceLang = "en"
            var sourceUrl: String? = null

            // А) Ищем автосгенерированные субтитры (ASR) через NewPipe
            // У автосгенерированного трека язык ВСЕГДА совпадает с реальной речью видео
            val autoSub = info.subtitles.orEmpty().find { it.isAutoGenerated }
            if (autoSub != null) {
                sourceLang = autoSub.languageTag.substringBefore("-")
                sourceUrl = autoSub.url
                Log.i(TAG, "🔍 [SUBTITLE_SOURCE] Истинный язык видео определен по ASR NewPipe: '$sourceLang'")
            } else {
                // Б) Пробуем через Innertube API (если NewPipe не нашел)
                val innertubeAsr = getInnertubeCaptionInfo(ytVideoId, targetLang = null)
                if (innertubeAsr != null) {
                    sourceUrl = innertubeAsr.first
                    sourceLang = innertubeAsr.second
                    Log.i(TAG, "🔍 [SUBTITLE_SOURCE] Истинный язык видео определен через Innertube: '$sourceLang'")
                } else {
                    // В) Фолбэк по языку аудиодорожки (если указан)
                    val audioLang = info.audioStreams.orEmpty().firstOrNull { it.audioLocale != null }?.audioLocale?.language
                    if (audioLang != null) {
                        sourceLang = audioLang
                        Log.i(TAG, "🔍 [SUBTITLE_SOURCE] Язык видео определен по аудиодорожке: '$sourceLang'")
                    } else {
                        Log.w(TAG, "🟠 [SUBTITLE_SOURCE] Язык не удалось определить. Фолбэк: '$sourceLang'")
                    }
                }
            }

            // Ищем качественные РУЧНЫЕ субтитры именно для найденного оригинального языка
            val manualSub = info.subtitles.orEmpty().find {
                !it.isAutoGenerated && it.languageTag.startsWith(sourceLang, ignoreCase = true)
            }

            if (manualSub != null) {
                sourceUrl = manualSub.url
                sourceLang = manualSub.languageTag.substringBefore("-")
                Log.i(TAG, "🟡 [SUBTITLE_SOURCE] ОРИГИНАЛ ($sourceLang): Найдена ручная дорожка.")
            } else if (sourceUrl != null) {
                Log.i(TAG, "🟡 [SUBTITLE_SOURCE] ОРИГИНАЛ ($sourceLang): Ручных сабов нет. Берем автосгенерированные (ASR).")
            } else {
                // Если ничего нет для исходного языка, берем первые попавшиеся
                val fallbackSub = info.subtitles.orEmpty().firstOrNull() ?: throw Exception("Субтитры отсутствуют полностью.")
                sourceUrl = fallbackSub.url
                sourceLang = fallbackSub.languageTag.substringBefore("-")
                Log.w(TAG, "🟠 [SUBTITLE_SOURCE] ОРИГИНАЛ ($sourceLang): Ничего не найдено, взят первый доступный язык.")
            }

            val finalSourceUrl = sourceUrl ?: throw Exception("Ссылка на субтитры пуста")

            // =================================================================
            // 2. ВЫБИРАЕМ АУДИО И ВИДЕО ПОТОКИ
            // =================================================================
            val allAudioStreams = info.audioStreams.orEmpty()
            val audioStream = allAudioStreams.filter { it.audioLocale?.language?.startsWith(sourceLang, true) == true }.maxByOrNull { it.averageBitrate }
                ?: allAudioStreams.filter { it.audioLocale == null }.maxByOrNull { it.averageBitrate }
                ?: allAudioStreams.maxByOrNull { it.averageBitrate }
                ?: throw Exception("Не найден аудиопоток")

            Log.i(TAG, "🎙️ [SUBTITLE_SOURCE] Выбран аудиопоток: ${audioStream.audioLocale?.language ?: "оригинал (без тега)"}")

            val allVideoStreams = info.videoOnlyStreams.orEmpty() + info.videoStreams.orEmpty()
            val videoStream = allVideoStreams.maxByOrNull { it.resolution.replace("p", "").toIntOrNull() ?: 0 }
                ?: allVideoStreams.firstOrNull() ?: throw Exception("Не найден видеопоток")

            // =================================================================
            // 3. ПРОВЕРКА КЭША
            // =================================================================
            val cachedEntities = subtitleBox.query(SubtitleBlockEntity_.youtubeVideoId.equal(videoId)).build().find()
            if (cachedEntities.isNotEmpty()) {
                Log.i(TAG, "🟢 [SUBTITLE_SOURCE] ВЗЯТО ИЗ КЭША (ObjectBox). Загружено ${cachedEntities.size} блоков.")
                val domainBlocks = cachedEntities.map {
                    SubtitleBlock(it.id, it.startTimeMs, it.endTimeMs, it.sourceText, it.translatedText)
                }.sortedBy { it.startTimeMs }

                return@withContext Result.success(VideoPlaybackInfo(videoStream.url.toString(),
                    audioStream.url.toString(), domainBlocks, true, sourceLang))
            }

            // =================================================================
            // 4. СКАЧИВАНИЕ И СМАРТ-ЧАНКИНГ ОРИГИНАЛА
            // =================================================================
            val rawSourceBlocks = fetchAndParseBlocks(finalSourceUrl)
            if (rawSourceBlocks.isEmpty()) throw Exception("Не удалось распарсить оригинальные субтитры.")

            val smartSourceBlocks = buildAestheticSubtitles(rawSourceBlocks)
            Log.i(TAG, "✅ [SUBTITLE_SOURCE] ОРИГИНАЛ: Собрано ${smartSourceBlocks.size} УМНЫХ ЧАНКОВ.")

            // =================================================================
            // 5. ПОЛУЧЕНИЕ ПЕРЕВОДА (RU)
            // =================================================================
            var ruBlocks = emptyList<SubtitleBlock>()
            try {
                if (sourceLang.startsWith("ru", true)) {
                    ruBlocks = smartSourceBlocks
                } else {
                    // Ищем ИМЕННО РУЧНЫЕ русские дорожки в данных от NewPipe (отсекая автосгенерированные)
                    val nativeRuUrl = info.subtitles.orEmpty().find {
                        !it.isAutoGenerated && it.languageTag.startsWith("ru", ignoreCase = true)
                    }?.url

                    if (nativeRuUrl != null) {
                        Log.i(TAG, "🔵 [SUBTITLE_SOURCE] РУС: Найдена качественная встроенная русская дорожка.")
                        ruBlocks = fetchAndParseBlocks(nativeRuUrl)
                    } else {
                        Log.i(TAG, "🟣 [SUBTITLE_SOURCE] РУС: Запрашиваем Автоперевод Ютуба.")
                        val ruUrl = if (finalSourceUrl.contains("tlang=")) finalSourceUrl else "$finalSourceUrl&tlang=ru"
                        try {
                            ruBlocks = fetchAndParseBlocks(ruUrl)
                        } catch (e: Exception) {
                            Log.w(TAG, "🟠 [SUBTITLE_SOURCE] РУС: Ошибка. Пытаемся обойти через Innertube API...")
                            val innertubeRuUrl = getInnertubeCaptionInfo(ytVideoId, targetLang = "ru")?.first
                            if (innertubeRuUrl != null) {
                                ruBlocks = fetchAndParseBlocks(innertubeRuUrl)
                            } else {
                                throw Exception("Innertube не вернул ссылку на перевод.")
                            }
                        }
                    }
                }
                if (ruBlocks.isEmpty()) throw Exception("Пустой ответ перевода.")
                Log.i(TAG, "✅ [SUBTITLE_SOURCE] РУС: Успешно получен перевод Ютуба (${ruBlocks.size} блоков).")
            } catch (e: Exception) {
                Log.w(TAG, "🔴 [SUBTITLE_SOURCE] РУС: Перевод YouTube недоступен. ML Kit всё переведет в фоне.")
            }

            // =================================================================
            // 6. СЛИЯНИЕ И СОХРАНЕНИЕ
            // =================================================================
            val mergedBlocks = if (ruBlocks.isNotEmpty()) mergeSubtitles(smartSourceBlocks, ruBlocks) else smartSourceBlocks

            val entitiesToSave = mergedBlocks.map {
                SubtitleBlockEntity(
                    youtubeVideoId = videoId,
                    startTimeMs = it.startTimeMs,
                    endTimeMs = it.endTimeMs,
                    sourceText = it.sourceText,
                    translatedText = it.translatedText
                )
            }
            subtitleBox.put(entitiesToSave)

            val savedBlocks = subtitleBox.query(SubtitleBlockEntity_.youtubeVideoId.equal(videoId)).build().find()
                .map { SubtitleBlock(it.id, it.startTimeMs, it.endTimeMs, it.sourceText, it.translatedText) }
                .sortedBy { it.startTimeMs }

            Result.success(
                VideoPlaybackInfo(
                    videoUrl = videoStream.url.toString(),
                    audioUrl = audioStream.url.toString(),
                    subtitles = savedBlocks,
                    hasYoutubeTranslation = ruBlocks.isNotEmpty(),
                    sourceLang = sourceLang
                )
            )
        } catch (e: Exception) {
            Log.e(TAG, "❌ [SUBTITLE_SOURCE] КРИТИЧЕСКАЯ ОШИБКА: ${e.message}")
            Result.failure(e)
        }
    }

    // ИЗМЕНЕНИЕ: Добавлен sourceLang, и он передается в translator
    override suspend fun translateAndSaveBlockLocally(block: SubtitleBlock, sourceLang: String): SubtitleBlock = withContext(Dispatchers.IO) {
        val translation = translator.translate(block.sourceText, sourceLang, "ru").getOrNull()
        val updatedBlock = block.copy(translatedText = translation ?: "Ошибка перевода")

        val entity = subtitleBox.get(block.id)
        if (entity != null) {
            entity.translatedText = updatedBlock.translatedText
            subtitleBox.put(entity)
        }
        updatedBlock
    }

    override suspend fun clearTranslationsForVideo(videoId: Long) {
        withContext(Dispatchers.IO) {
            val blocks = subtitleBox.query(SubtitleBlockEntity_.youtubeVideoId.equal(videoId)).build().find()
            blocks.forEach { it.translatedText = null }
            subtitleBox.put(blocks)
        }
    }

    // =======================================================================
    // СМАРТ-ЧАНКИНГ (СИНТАКСИЧЕСКОЕ РАЗБИЕНИЕ)
    // =======================================================================

    private data class TimedWord(val text: String, val start: Long, val end: Long)

    private fun buildAestheticSubtitles(rawBlocks: List<SubtitleBlock>): List<SubtitleBlock> {
        if (rawBlocks.isEmpty()) return emptyList()

        val allWords = mutableListOf<TimedWord>()
        for (block in rawBlocks) {
            val words = block.sourceText.split(Regex("\\s+")).filter { it.isNotBlank() }
            if (words.isEmpty()) continue

            val duration = maxOf(1L, block.endTimeMs - block.startTimeMs)
            val timePerWord = duration / words.size

            words.forEachIndexed { i, word ->
                allWords.add(TimedWord(
                    text = word,
                    start = block.startTimeMs + (i * timePerWord),
                    end = block.startTimeMs + ((i + 1) * timePerWord)
                ))
            }
        }

        val logicalSentences = mutableListOf<List<TimedWord>>()
        var currentSentence = mutableListOf<TimedWord>()

        for (i in allWords.indices) {
            val word = allWords[i]
            currentSentence.add(word)

            val endsWithPunctuation = word.text.lastOrNull() in listOf('.', '!', '?')
            val isNextWordFar = if (i < allWords.size - 1) {
                (allWords[i + 1].start - word.end) > 1500L
            } else false

            val isTooLong = currentSentence.joinToString(" ") { it.text }.length > 150

            if (endsWithPunctuation || isNextWordFar || isTooLong) {
                logicalSentences.add(currentSentence)
                currentSentence = mutableListOf()
            }
        }
        if (currentSentence.isNotEmpty()) logicalSentences.add(currentSentence)

        var idCounter = 0L
        val finalBlocks = mutableListOf<SubtitleBlock>()

        for (sentence in logicalSentences) {
            val chunks = splitSentenceSmartly(sentence)
            for (chunk in chunks) {
                if (chunk.isEmpty()) continue
                finalBlocks.add(SubtitleBlock(
                    id = idCounter++,
                    startTimeMs = chunk.first().start,
                    endTimeMs = chunk.last().end,
                    sourceText = chunk.joinToString(" ") { it.text }
                ))
            }
        }

        return finalBlocks
    }

    // =======================================================================
    // СМАРТ-ЧАНКИНГ (СИНТАКСИЧЕСКОЕ РАЗБИЕНИЕ)
    // =======================================================================

    private fun splitSentenceSmartly(sentence: List<TimedWord>): List<List<TimedWord>> {
        val text = sentence.joinToString(" ") { it.text }

        if (text.length <= 85 || sentence.size <= 5) {
            return listOf(sentence)
        }

        var bestSplitIndex = -1
        var maxScore = Int.MIN_VALUE

        // Расширенный список для Английского и Французского языков
        val conjunctions = setOf(
            // EN
            "and", "but", "so", "because", "until", "while", "after", "before", "when", "which", "that", "who", "where", "if",
            // FR
            "et", "ou", "mais", "donc", "car", "parce", "que", "qui", "quand", "si", "comme", "puisque"
        )
        val orphans = setOf(
            // EN
            "a", "an", "the", "in", "on", "at", "to", "for", "of", "with", "by", "from", "is", "are", "was", "were", "am", "i", "you", "he", "she", "it", "we", "they", "my", "your", "his", "her", "our", "their",
            // FR (включая апострофы)
            "le", "la", "les", "un", "une", "des", "de", "du", "d'", "l'", "à", "au", "aux", "dans", "sur", "en", "vers", "avec", "sans", "sous", "par", "pour", "je", "tu", "il", "elle", "on", "nous", "vous", "ils", "elles", "mon", "ton", "son", "ma", "ta", "sa", "mes", "tes", "ses", "est", "sont", "suis", "es", "c'", "c", "qu'", "qu"
        )

        for (i in 2 until sentence.size - 2) {
            var score = 0

            val wordBeforeRaw = sentence[i - 1].text
            val wordAfterRaw = sentence[i].text

            // ИСПРАВЛЕНИЕ: Используем \p{L} для поддержки всех алфавитов (включая é, à, ç и т.д.)
            val wordBefore = wordBeforeRaw.lowercase().replace(Regex("[^\\p{L}']"), "")
            val wordAfter = wordAfterRaw.lowercase().replace(Regex("[^\\p{L}']"), "")

            if (wordBeforeRaw.endsWith(",")) score += 100
            if (wordBeforeRaw.endsWith(";") || wordBeforeRaw.endsWith("-")) score += 80
            if (wordAfter in conjunctions) score += 90

            if (wordBefore in orphans) score -= 500
            if (wordAfterRaw.matches(Regex(".*[.!?,]$"))) score -= 500

            val leftSize = i
            val rightSize = sentence.size - i

            if (leftSize < 3 || rightSize < 3) score -= 1000

            val diff = abs(leftSize - rightSize)
            score -= (diff * 5)

            if (score > maxScore) {
                maxScore = score
                bestSplitIndex = i
            }
        }

        if (bestSplitIndex == -1 || maxScore <= -100) {
            bestSplitIndex = sentence.size / 2
        }

        val leftChunk = sentence.subList(0, bestSplitIndex)
        val rightChunk = sentence.subList(bestSplitIndex, sentence.size)

        val result = mutableListOf<List<TimedWord>>()
        result.addAll(splitSentenceSmartly(leftChunk))
        result.addAll(splitSentenceSmartly(rightChunk))

        return result
    }

    // ====================== ALGORITHM: 2-PASS OVERLAP MERGE ======================
    private val endSentenceRegex = Regex(".*[.!?…]+[\"'\\]»]*$")

    // ====================== ALGORITHM: TIME-INTERPOLATION + SEMANTIC SEAM ADJUSTER ======================

    private fun mergeSubtitles(smartSourceBlocks: List<SubtitleBlock>, rawRuBlocks: List<SubtitleBlock>): List<SubtitleBlock> {
        if (smartSourceBlocks.isEmpty() || rawRuBlocks.isEmpty()) return smartSourceBlocks

        // 1. Упаковываем все русские слова в один поток с аппроксимированными таймкодами (интерполяция)
        val ruWords = mutableListOf<TimedWord>()
        for (ru in rawRuBlocks) {
            val words = ru.sourceText.split(Regex("\\s+")).filter { it.isNotBlank() }
            if (words.isEmpty()) continue
            val duration = maxOf(1L, ru.endTimeMs - ru.startTimeMs)
            val timePerWord = duration / words.size
            words.forEachIndexed { i, w ->
                ruWords.add(TimedWord(w, ru.startTimeMs + (i * timePerWord), ru.startTimeMs + ((i + 1) * timePerWord)))
            }
        }

        // 2. Первичное (черновое) распределение слов по французским блокам на основе времени
        val blockAllocations = Array(smartSourceBlocks.size) { mutableListOf<TimedWord>() }
        for (ruWord in ruWords) {
            val wordCenter = (ruWord.start + ruWord.end) / 2
            var bestIndex = -1
            var minDistance = Long.MAX_VALUE

            for (i in smartSourceBlocks.indices) {
                val smart = smartSourceBlocks[i]
                if (wordCenter in smart.startTimeMs..smart.endTimeMs) {
                    bestIndex = i
                    break
                } else {
                    val dist = minOf(Math.abs(wordCenter - smart.startTimeMs), Math.abs(wordCenter - smart.endTimeMs))
                    if (dist < minDistance) {
                        minDistance = dist
                        bestIndex = i
                    }
                }
            }
            if (bestIndex != -1) blockAllocations[bestIndex].add(ruWord)
        }

        // 3. МАГИЯ: Семантическое сглаживание швов (Semantic Seam Adjuster)
        val ruConjunctions = setOf("и", "а", "но", "да", "или", "либо", "что", "чтобы", "как", "если", "хотя", "где", "когда", "который", "которая", "потому", "поэтому", "так", "затем", "потом", "ведь", "чем")
        val ruDangling = setOf("в", "на", "с", "к", "от", "из", "у", "за", "над", "под", "о", "об", "для", "до", "без", "не", "ни")

        for (i in 0 until smartSourceBlocks.size - 1) {
            val currentWords = blockAllocations[i]
            val nextWords = blockAllocations[i + 1]

            if (currentWords.isEmpty() && nextWords.isEmpty()) continue

            // Создаем окно из 8 слов вокруг математического "шва" (4 слева, 4 справа)
            val windowSize = 4
            val leftPart = currentWords.takeLast(windowSize)
            val rightPart = nextWords.take(windowSize)
            val window = leftPart + rightPart

            if (window.isEmpty()) continue

            val originalCutIndex = leftPart.size
            var bestCutIndex = originalCutIndex
            var maxScore = -1000

            // Перебираем все возможные места разреза внутри окна
            for (k in 1 until window.size) {
                var score = 0
                val wordBefore = window[k - 1].text.lowercase()
                val wordAfter = window[k].text.lowercase()
                val cleanWordBefore = wordBefore.replace(Regex("[^а-яё]"), "")
                val cleanWordAfter = wordAfter.replace(Regex("[^а-яё]"), "")

                // Правило 1: Идеально резать после пунктуации
                if (wordBefore.matches(Regex(".*[,.!?;:][\"'\\]»]*$"))) score += 100

                // Правило 2: Хорошо, если новый блок начинается с союза (так, что, как)
                if (cleanWordAfter in ruConjunctions) score += 50

                // Правило 3: КАТЕГОРИЧЕСКИ ЗАПРЕЩЕНО оставлять предлог висеть в конце блока
                if (cleanWordBefore in ruDangling) score -= 200

                // Правило 4: Начинать блок с предлога — это правильно и естественно
                if (cleanWordAfter in ruDangling) score += 20

                // Правило 5: Штраф за слишком сильное отдаление от таймкода
                val distance = Math.abs(k - originalCutIndex)
                score -= (distance * 15)

                if (score > maxScore) {
                    maxScore = score
                    bestCutIndex = k
                }
            }

            // Применяем лучший найденный разрез, "переливая" слова между блоками
            if (bestCutIndex != originalCutIndex && maxScore > -500) {
                val shift = bestCutIndex - originalCutIndex
                if (shift > 0) {
                    // Перемещаем слова из начала следующего блока в конец текущего
                    val wordsToMove = nextWords.take(shift)
                    currentWords.addAll(wordsToMove)
                    blockAllocations[i + 1] = nextWords.drop(shift).toMutableList()
                } else {
                    // Перемещаем слова (например, висячие предлоги) из текущего в следующий
                    val absShift = Math.abs(shift)
                    val wordsToMove = currentWords.takeLast(absShift)
                    nextWords.addAll(0, wordsToMove)
                    blockAllocations[i] = currentWords.dropLast(absShift).toMutableList()
                }
            }
        }

        // 4. Сборка итогового текста
        return smartSourceBlocks.mapIndexed { i, smart ->
            val mergedText = blockAllocations[i].joinToString(" ") { it.text }.takeIf { it.isNotBlank() }
            smart.copy(translatedText = mergedText)
        }
    }
    // ====================== INNERTUBE API FALLBACK ======================

    private fun getInnertubeCaptionInfo(videoId: String, targetLang: String? = null): Pair<String, String>? {
        try {
            val body = JSONObject().apply {
                put("videoId", videoId)
                put("context", JSONObject().apply {
                    put("client", JSONObject().apply {
                        put("clientName", "WEB")
                        put("clientVersion", "2.20250601.01.00")
                        put("hl", "en") // Важно использовать "en", чтобы не было багов с локализацией
                    })
                })
            }

            val request = Request(
                "POST",
                "https://www.youtube.com/youtubei/v1/player",
                mapOf(
                    "Content-Type" to listOf("application/json"),
                    "User-Agent" to listOf("Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36")
                ),
                body.toString().toByteArray(Charsets.UTF_8),
                null,
                false
            )

            val response = NewPipeDownloader.getInstance().execute(request)
            if (response.responseCode() in 200..299) {
                val json = JSONObject(response.responseBody())
                val tracks = json.optJSONObject("captions")
                    ?.optJSONObject("playerCaptionsTracklistRenderer")
                    ?.optJSONArray("captionTracks") ?: return null

                var bestTrack: JSONObject? = null

                if (targetLang != null) {
                    // Ищем ручные сабы для целевого языка
                    for (i in 0 until tracks.length()) {
                        val t = tracks.optJSONObject(i) ?: continue
                        val vssId = t.optString("vssId", "")
                        if (t.optString("languageCode").startsWith(targetLang, ignoreCase = true) && !vssId.startsWith("a.")) {
                            bestTrack = t
                            break
                        }
                    }
                    // Если нет ручных, берем любые (например, переведенные авто)
                    if (bestTrack == null) {
                        for (i in 0 until tracks.length()) {
                            val t = tracks.optJSONObject(i) ?: continue
                            if (t.optString("languageCode").startsWith(targetLang, ignoreCase = true)) {
                                bestTrack = t
                                break
                            }
                        }
                    }
                } else {
                    // ИЩЕМ ОРИГИНАЛЬНЫЙ ЯЗЫК АУДИО (ASR)
                    for (i in 0 until tracks.length()) {
                        val t = tracks.optJSONObject(i) ?: continue
                        val vssId = t.optString("vssId", "")
                        val kind = t.optString("kind", "")
                        // vssId начинается с "a." означает auto-generated (сгенерировано движком YouTube).
                        // Это 100% гарантия того, что это оригинальный язык речи.
                        if (kind == "asr" || vssId.startsWith("a.")) {
                            bestTrack = t
                            break
                        }
                    }
                }

                if (bestTrack != null) {
                    var url = bestTrack.optString("baseUrl")
                    val lang = bestTrack.optString("languageCode").substringBefore("-")

                    if (targetLang != null && !url.contains("tlang=")) {
                        url += if (url.contains("?")) "&tlang=$targetLang" else "?tlang=$targetLang"
                    }
                    url = url.replace(Regex("fmt=[^&]+"), "fmt=json3").let {
                        if (!it.contains("fmt=json3")) "$it&fmt=json3" else it
                    }
                    return Pair(url, lang)
                }
            }
        } catch (e: Exception) {
            e.printStackTrace()
        }
        return null
    }

    // ====================== ПАРСИНГ И СКАЧИВАНИЕ ======================

    private fun fetchAndParseBlocks(url: String): List<SubtitleBlock> {
        val urlsToTry = listOf(
            url.replace(Regex("fmt=[^&]+"), "fmt=json3").let { if (!it.contains("fmt=json3")) "$it&fmt=json3" else it },
            url.replace(Regex("fmt=[^&]+"), "fmt=srv1").let { if (!it.contains("fmt=srv1")) "$it&fmt=srv1" else it }
        )

        for (u in urlsToTry) {
            try {
                val raw = downloadString(u)
                val jsonBlocks = parseJson3(raw)
                if (jsonBlocks.isNotEmpty()) return jsonBlocks

                val xmlBlocks = parseSubtitles(raw)
                if (xmlBlocks.isNotEmpty()) return xmlBlocks
            } catch (e: Exception) { continue }
        }
        return emptyList()
    }

    private fun downloadString(urlStr: String): String {
        val request = Request("GET", urlStr, emptyMap(), null, null, false)
        val response = NewPipeDownloader.getInstance().execute(request)
        val code = response.responseCode()
        if (code in 200..299) return response.responseBody() else throw Exception("HTTP $code")
    }

    private fun parseJson3(json: String): List<SubtitleBlock> {
        val blocks = mutableListOf<SubtitleBlock>()
        try {
            val root = JSONObject(json)
            val events = root.optJSONArray("events") ?: return blocks
            var id = 0L

            for (i in 0 until events.length()) {
                val event = events.optJSONObject(i) ?: continue
                val startMs = event.optLong("tStartMs", 0L)
                val durMs = event.optLong("dDurationMs", 0L)
                val segs = event.optJSONArray("segs") ?: continue

                val text = buildString {
                    for (j in 0 until segs.length()) append(segs.optJSONObject(j)?.optString("utf8", ""))
                }.replace("\n", " ").trim()

                if (text.isBlank()) continue

                blocks.add(SubtitleBlock(id++, startMs, startMs + durMs, text))
            }
        } catch (e: Exception) { }
        return blocks
    }

    private fun parseSubtitles(xml: String): List<SubtitleBlock> {
        val blocks = mutableListOf<SubtitleBlock>()
        val pattern = Pattern.compile("<text start=\"([\\d.]+)\"(?: dur=\"([\\d.]+)\")?[^>]*>(.*?)</text>", Pattern.DOTALL)
        val matcher = pattern.matcher(xml)
        var id = 0L

        while (matcher.find()) {
            val startSec = matcher.group(1)?.toFloatOrNull() ?: continue
            val durSec = matcher.group(2)?.toFloatOrNull() ?: 2.0f
            var text = matcher.group(3) ?: continue

            text = text.replace("&amp;", "&").replace("&quot;", "\"").replace("&#39;", "'").replace("&lt;", "<").replace("&gt;", ">").replace("\n", " ").replace(Regex("<[^>]*>"), "").trim()
            if (text.isBlank()) continue
            blocks.add(SubtitleBlock(id++, (startSec * 1000).toLong(), ((startSec + durSec) * 1000).toLong(), text))
        }
        return blocks
    }

    private fun extractVideoId(url: String): String? {
        val regex = Regex("(?:v=|youtu\\.be/|embed/|shorts/)([\\w-]{11})")
        return regex.find(url)?.groupValues?.get(1)
    }

    private fun YoutubeVideoEntity.toDomain() = YoutubeVideo(id, videoUrl, title, thumbnailUrl, progressMs, durationMs)
}